login:
    pattern:  /login
    defaults: { _controller: "UserBundle:Login:login" }

login_check:
    pattern:  /login_check
    defaults: { _controller: "UserBundle:Login:loginCheck" }

logout:
    pattern : /logout
    defaults: {_controller: "UserBundle:Login:logout"}